#ifndef ALL_SOLVED_TREE_RECORD_IDS_RANK_CASE_TWO_TEST_H
#define ALL_SOLVED_TREE_RECORD_IDS_RANK_CASE_TWO_TEST_H

void test_all_solved_tree_record_ids_rank_case_two(void);

#endif // ALL_SOLVED_TREE_RECORD_IDS_RANK_CASE_TWO_TEST_H
