version: "3.9"
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
    command: redis-server
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112223
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112223
    restart: always
    volumes:
      - .:/akadan
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq -C ./sidekiq.yml
    volumes:
      - .:/akadan
  cable:
    depends_on:
      - redis
    build: .
    command: puma -p 28080
    ports:
      - '28080:28080'
    volumes:
      - .:/akadan

volumes:
  postgres:
  bundler_gems:
  redis:
