version: "3.9"
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    env_file:
      - .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/akadan
      - bundler_gems:/usr/local/bundle/
    ports:
      - "80:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    depends_on:
      - db
      - redis
      - webpack
    environment:
      - RAILS_SERVE_STATIC_FILES=false
  webpack:
    command: ./bin/webpack-dev-server
    build: .
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  sidekiq:
    env_file:
      - .env
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -e development -C config/sidekiq.yml
    volumes:
      - .:/akadan
  cable:
    env_file:
      - .env
    depends_on:
      - redis
    build: .
    command: puma -p 28080
    ports:
      - '28080:28080'
    volumes:
      - .:/akadan

volumes:
  postgres:
  bundler_gems:
  redis:
