 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comments", type: :request do
  let!(:user) { create(:user) }
  let!(:record) { create(:record) }

  # Comment. As you add validations to Comment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      body: 'my comment'
    }
  }

  let(:invalid_attributes) {
    {
      body: ''
    }
  }

  describe "GET /new" do
    it "renders a successful response" do
      get new_record_comment_url(record, format: :js)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    before { sign_in user }

    context "with valid parameters" do
      it "creates a new Comment" do
        expect {
          post record_comments_url(record, format: :js), params: { comment: valid_attributes }
        }.to change(record.comments, :count).by(1)
      end

      it "render comment" do
        post record_comments_url(record, format: :js), params: { comment: valid_attributes }
        expect(response).to render_template :show
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comment" do
        expect {
          post record_comments_url(record, format: :js), params: { comment: invalid_attributes }
        }.to change(Comment, :count).by(1)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post record_comments_url(record, format: :js), params: { comment: invalid_attributes }
        expect(response).to render_template :show
      end
    end
  end
end
