 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/connection_types", type: :request do
  
  # ConnectionType. As you add validations to ConnectionType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ConnectionType.create! valid_attributes
      get connection_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      connection_type = ConnectionType.create! valid_attributes
      get connection_type_url(connection_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_connection_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      connection_type = ConnectionType.create! valid_attributes
      get edit_connection_type_url(connection_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConnectionType" do
        expect {
          post connection_types_url, params: { connection_type: valid_attributes }
        }.to change(ConnectionType, :count).by(1)
      end

      it "redirects to the created connection_type" do
        post connection_types_url, params: { connection_type: valid_attributes }
        expect(response).to redirect_to(connection_type_url(ConnectionType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConnectionType" do
        expect {
          post connection_types_url, params: { connection_type: invalid_attributes }
        }.to change(ConnectionType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post connection_types_url, params: { connection_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested connection_type" do
        connection_type = ConnectionType.create! valid_attributes
        patch connection_type_url(connection_type), params: { connection_type: new_attributes }
        connection_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the connection_type" do
        connection_type = ConnectionType.create! valid_attributes
        patch connection_type_url(connection_type), params: { connection_type: new_attributes }
        connection_type.reload
        expect(response).to redirect_to(connection_type_url(connection_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        connection_type = ConnectionType.create! valid_attributes
        patch connection_type_url(connection_type), params: { connection_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested connection_type" do
      connection_type = ConnectionType.create! valid_attributes
      expect {
        delete connection_type_url(connection_type)
      }.to change(ConnectionType, :count).by(-1)
    end

    it "redirects to the connection_types list" do
      connection_type = ConnectionType.create! valid_attributes
      delete connection_type_url(connection_type)
      expect(response).to redirect_to(connection_types_url)
    end
  end
end
