 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/conversations", type: :request do
  
  # Conversation. As you add validations to Conversation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Conversation.create! valid_attributes
      get conversations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      conversation = Conversation.create! valid_attributes
      get conversation_url(conversation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_conversation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      conversation = Conversation.create! valid_attributes
      get edit_conversation_url(conversation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Conversation" do
        expect {
          post conversations_url, params: { conversation: valid_attributes }
        }.to change(Conversation, :count).by(1)
      end

      it "redirects to the created conversation" do
        post conversations_url, params: { conversation: valid_attributes }
        expect(response).to redirect_to(conversation_url(Conversation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Conversation" do
        expect {
          post conversations_url, params: { conversation: invalid_attributes }
        }.to change(Conversation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post conversations_url, params: { conversation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conversation" do
        conversation = Conversation.create! valid_attributes
        patch conversation_url(conversation), params: { conversation: new_attributes }
        conversation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the conversation" do
        conversation = Conversation.create! valid_attributes
        patch conversation_url(conversation), params: { conversation: new_attributes }
        conversation.reload
        expect(response).to redirect_to(conversation_url(conversation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        conversation = Conversation.create! valid_attributes
        patch conversation_url(conversation), params: { conversation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested conversation" do
      conversation = Conversation.create! valid_attributes
      expect {
        delete conversation_url(conversation)
      }.to change(Conversation, :count).by(-1)
    end

    it "redirects to the conversations list" do
      conversation = Conversation.create! valid_attributes
      delete conversation_url(conversation)
      expect(response).to redirect_to(conversations_url)
    end
  end
end
