 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dots", type: :request do
  
  # Dot. As you add validations to Dot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Dot.create! valid_attributes
      get dots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dot = Dot.create! valid_attributes
      get dot_url(dot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dot = Dot.create! valid_attributes
      get edit_dot_url(dot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dot" do
        expect {
          post dots_url, params: { dot: valid_attributes }
        }.to change(Dot, :count).by(1)
      end

      it "redirects to the created dot" do
        post dots_url, params: { dot: valid_attributes }
        expect(response).to redirect_to(dot_url(Dot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dot" do
        expect {
          post dots_url, params: { dot: invalid_attributes }
        }.to change(Dot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dots_url, params: { dot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dot" do
        dot = Dot.create! valid_attributes
        patch dot_url(dot), params: { dot: new_attributes }
        dot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dot" do
        dot = Dot.create! valid_attributes
        patch dot_url(dot), params: { dot: new_attributes }
        dot.reload
        expect(response).to redirect_to(dot_url(dot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dot = Dot.create! valid_attributes
        patch dot_url(dot), params: { dot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dot" do
      dot = Dot.create! valid_attributes
      expect {
        delete dot_url(dot)
      }.to change(Dot, :count).by(-1)
    end

    it "redirects to the dots list" do
      dot = Dot.create! valid_attributes
      delete dot_url(dot)
      expect(response).to redirect_to(dots_url)
    end
  end
end
