 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/message_chains", type: :request do
  
  # MessageChain. As you add validations to MessageChain, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MessageChain.create! valid_attributes
      get message_chains_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      message_chain = MessageChain.create! valid_attributes
      get message_chain_url(message_chain)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_message_chain_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      message_chain = MessageChain.create! valid_attributes
      get edit_message_chain_url(message_chain)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MessageChain" do
        expect {
          post message_chains_url, params: { message_chain: valid_attributes }
        }.to change(MessageChain, :count).by(1)
      end

      it "redirects to the created message_chain" do
        post message_chains_url, params: { message_chain: valid_attributes }
        expect(response).to redirect_to(message_chain_url(MessageChain.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MessageChain" do
        expect {
          post message_chains_url, params: { message_chain: invalid_attributes }
        }.to change(MessageChain, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post message_chains_url, params: { message_chain: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested message_chain" do
        message_chain = MessageChain.create! valid_attributes
        patch message_chain_url(message_chain), params: { message_chain: new_attributes }
        message_chain.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the message_chain" do
        message_chain = MessageChain.create! valid_attributes
        patch message_chain_url(message_chain), params: { message_chain: new_attributes }
        message_chain.reload
        expect(response).to redirect_to(message_chain_url(message_chain))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        message_chain = MessageChain.create! valid_attributes
        patch message_chain_url(message_chain), params: { message_chain: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested message_chain" do
      message_chain = MessageChain.create! valid_attributes
      expect {
        delete message_chain_url(message_chain)
      }.to change(MessageChain, :count).by(-1)
    end

    it "redirects to the message_chains list" do
      message_chain = MessageChain.create! valid_attributes
      delete message_chain_url(message_chain)
      expect(response).to redirect_to(message_chains_url)
    end
  end
end
