 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/record_types", type: :request do
  
  # RecordType. As you add validations to RecordType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RecordType.create! valid_attributes
      get record_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      record_type = RecordType.create! valid_attributes
      get record_type_url(record_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_record_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      record_type = RecordType.create! valid_attributes
      get edit_record_type_url(record_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RecordType" do
        expect {
          post record_types_url, params: { record_type: valid_attributes }
        }.to change(RecordType, :count).by(1)
      end

      it "redirects to the created record_type" do
        post record_types_url, params: { record_type: valid_attributes }
        expect(response).to redirect_to(record_type_url(RecordType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RecordType" do
        expect {
          post record_types_url, params: { record_type: invalid_attributes }
        }.to change(RecordType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post record_types_url, params: { record_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested record_type" do
        record_type = RecordType.create! valid_attributes
        patch record_type_url(record_type), params: { record_type: new_attributes }
        record_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the record_type" do
        record_type = RecordType.create! valid_attributes
        patch record_type_url(record_type), params: { record_type: new_attributes }
        record_type.reload
        expect(response).to redirect_to(record_type_url(record_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        record_type = RecordType.create! valid_attributes
        patch record_type_url(record_type), params: { record_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested record_type" do
      record_type = RecordType.create! valid_attributes
      expect {
        delete record_type_url(record_type)
      }.to change(RecordType, :count).by(-1)
    end

    it "redirects to the record_types list" do
      record_type = RecordType.create! valid_attributes
      delete record_type_url(record_type)
      expect(response).to redirect_to(record_types_url)
    end
  end
end
