 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/seminars", type: :request do
  
  # Seminar. As you add validations to Seminar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Seminar.create! valid_attributes
      get seminars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      seminar = Seminar.create! valid_attributes
      get seminar_url(seminar)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_seminar_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      seminar = Seminar.create! valid_attributes
      get edit_seminar_url(seminar)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Seminar" do
        expect {
          post seminars_url, params: { seminar: valid_attributes }
        }.to change(Seminar, :count).by(1)
      end

      it "redirects to the created seminar" do
        post seminars_url, params: { seminar: valid_attributes }
        expect(response).to redirect_to(seminar_url(Seminar.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Seminar" do
        expect {
          post seminars_url, params: { seminar: invalid_attributes }
        }.to change(Seminar, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post seminars_url, params: { seminar: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested seminar" do
        seminar = Seminar.create! valid_attributes
        patch seminar_url(seminar), params: { seminar: new_attributes }
        seminar.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the seminar" do
        seminar = Seminar.create! valid_attributes
        patch seminar_url(seminar), params: { seminar: new_attributes }
        seminar.reload
        expect(response).to redirect_to(seminar_url(seminar))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        seminar = Seminar.create! valid_attributes
        patch seminar_url(seminar), params: { seminar: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested seminar" do
      seminar = Seminar.create! valid_attributes
      expect {
        delete seminar_url(seminar)
      }.to change(Seminar, :count).by(-1)
    end

    it "redirects to the seminars list" do
      seminar = Seminar.create! valid_attributes
      delete seminar_url(seminar)
      expect(response).to redirect_to(seminars_url)
    end
  end
end
