default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['REAL'] ? 'db' : 'localhost' %>
  username: postgres
  password: 112223
  pool: 50000

development:
  <<: *default
  database: akadan_development


test:
  <<: *default
  database: akadan_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: akadan_production
