# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 112223
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: journal_development

test:
  <<: *default
  database: journal_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: journal_production
  # In production, you might want to set additional configurations
  # like URL, username, and password from environment variables.
  # Example:
  # url: <%= ENV['DATABASE_URL'] %>
